### ISSUE TITLE
Missing modules on ivyroundup

### ISSUE THREAD

**Issue by mkr3mer** [archiecobbs/jvser#2]
Not sure if this counts as a bug for this project, but some dependencies from ivy roundup are no longer present.

javax.comm
http://archiecobbs.github.io/ivyroundup/repo/modules/javax.comm/comm/3.0.u1/ivy.xml
The resource URL is no longer available.
I found a copy at http://www.scottsbots.com/downloads/comm3.0_u1_linux.zip

org.testng#testng;[5.10,6.0[
http://archiecobbs.github.io/ivyroundup/repo/modules/org.testng/testng/[revision]/ivy.xml
Only revisions: 6.8.7, 6.8, 6.7, 6.2.1, 5.8, 5.7 are available.
I tried building with 6.2.1 and it succeeded.

**Comment by archiecobbs** [comment]
Thanks. Fixed in https://github.com/archiecobbs/ivyroundup/commit/9051dcce9138e1cab173ca777eaeacfacebb7f32
